/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ep202411.jr0417;

import java.util.Scanner;

/*
Скорость ветра
*/                       
                                                        
public class Solution {
    public static void main(String[] args) {
        //напишите тут ваш код
        Scanner scanner  =  new Scanner  (System.in);
        int inputWindVelocity  = scanner.nextInt();
        int outWindVelocity = (int)Math.round((inputWindVelocity * 3.6));
        System.out.println(outWindVelocity);
    }
}
